name: Extension CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  node-version: 12.x

jobs:
  deploy:

    name: Package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

    - name: Setup .NET SDK 3.1.408
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.408

    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - run: npm install
    - run: npm run deploy

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: artifacts-view-avalonia-preview-vscode
        path: ./*.vsix
